
language: ruby
rvm:
  - 2.2.2

script: 
  - "bundle exec jekyll build"
  - "bundle exec htmlproofer ./_site --disable-external --allow-hash-href"  

after_script:
  - ./cloudflare_reset.sh
branches:
  only:
    - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
  - secure: pS9ZPNpI+MTBpVgQ6lUSuLjpYTopmLJsOna6bZmKaOxRw4dNkguwZriSdKUHMuvIHe5qXR8uwYLjkQ4UlePlZjT+AZOrWrdy8TNv4lJq11qL2qDOVr5g23KlUOBwgFF/jRbbf8bNgIZuv0lMQ6O9tyVNq0o/+1blXE3EOGA4YWFmH+BD0bwfXBs9+agufpOUf2n51hlMcjdYQntwkBTLNF4bQtzl+JAQhmgqx+hKmdNgYxf7DIRnYmbHyUbyKchwb8l5BO01u4vXqP8KPevFv6xlRfbXlfXLyE66MqihV8xeG2NP68NVs0QYorrIslN1CdZXMbhWNvcBnLfld1PPUZCGm7zvMA/3hpFK2Nc1L62YIDsj9V/lGmDhyVmJHuezbyxDX+a7tGeVDixGIT+e/bOjE3wl6jhXEjGN47eSohUV/wfLg8uk7kEA2TZrtR+Y6wUIMSLJqDoAYiI0aW7VWsyipYrsp8iJti5RCK1zzAmpjzmT8oyZhxwLary/XPjtPVKuFR+7KmFB5zeizuRAWCBIdv/Q29h8DV6ZUHvcZtEWyYxX4iAs2i0ztJaOZiSL0egGfyJEoLj6Tuiv93Aw+DgWZ4oBtnBba5JEi8gR16qjgGDxJGWaHfA3Sd4LAbL1D4O4GlW4BaOl8NlVSKMy1pc7RCSOGovjlbZ9io0VbEM=
  - secure: ENJJRzeiMCLRkzgVojITQiJ4lgtr5y/T+F6FkID56nPoqzajxz7qugbDu46IGs73KNwPoOE/2Jnn2KabCWjTqxlLKWOz18puHe7Sj4M5p99tR/Rc/2m7rgQNuVVjbCm2XbAft/RJPJklfevqgfw8qaT+BYK8xZtVhdzdythCUqDtPBOI4L/G/l531QoisLHeZUrnWlnHehcCVFR/ll3nMZWd0hDejK+DWmhdzsL3leu1BdbLaCdE1fZDXiQDIQWFF79Dq5RissSeB+WwJYZFSmCpVgoX3xCU7vOQHg3ydLes6o/pbhoQbideKR6KU4eD5TbZZqKrb4XRX53dYW0DIrrpIioi83aCygOi/1CeDiiObZKQFIFmaA8Ns0klToupKHC5nWV/55J1iN1yJdi8ry6zEyHHj3GJLikwFCjNzQbwU0z2V1F6An97uHE+0Uq7EfAV8IIardTVd5qkmluOhECGns9gDzMxriKgt8Jq6MbhVflXneVMowAIl+b5B85O9QJQ6aOcsC1eKyjRMoLIwVCbDEM2ya2nDr9Aq8974suaKk0hmRTYLpfCQo+5kqntumyRwYWmpwIyy4LrlTu9OI1pt/GLEL5NfPbn5DLx3Zc7wDogHJSXV4ioKjIYycZPrx+QYt9p+tZZ+hoq+5BWX7SQU/3pD7ttiK0tsqQCPHw=
