
language: ruby
rvm:
  - 2.2.2

script: 
  - "bundle exec jekyll build"
  - "bundle exec htmlproofer ./_site --disable-external --allow-hash-href"  

after_script:
  - ./cloudflare_reset.sh
branches:
  only:
    - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
