# Site settings
title: Massachusetts Reptile Expo
email: webmaster@massreptileexpo.com
description: > # this means to ignore newlines until "baseurl:"
  The Massachusetts Reptile Expo is an all-volunteer run event sponsored by the 
  New England Herpetological Society and the Brockton Rox. 
  All proceeds go towards herpetological research projects within the New England area.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://massreptileexpo.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
include: ['_pages']
